# Numpy basics and theroy 
NumPy exists to provide standard Python with a highly efficient, multi-dimensional array structure capable of performing fast numerical computations. While standard Python is highly flexible and easy to write, it lacks a built-in multi-dimensional array structure and is notoriously slow when handling large datasets or heavy mathematical operations.

In [52]:
import numpy as np # import numpy libary 
a = np.array([4,5,6,7,8,9]) # create a numpy array
print(a) # print the array

b = np.array(([1,2,4,5],[7,9,6,9])) # create a 2D numpy array 
print(b) # print the 2D array

c = np.zeros((4,6)) # create a 4x6 array of zeros
print(c) # print the array of zeros

d = np.zeros((4))
print(d) # print the 1D array of zeros

e = np.ones ((5))
print(e) # print the 1D array of ones

f = np.ones((5,3)) # create a 5x3 array of ones
print(f) # print the array of ones

g = np.full((6,3),5) # create a 6x3 array filled with 5
print(g) # print the array filled with 5

h = np.arange(10) # create an array with values from 0 to 9
print(h) # print the array

i = np.arange(5,15) # create an array with values from 5 to 14
print(i) # print the array

j = np.arange(5,15,2) # create an array with values from 5 to 14 with a step of 2
print(j) # print the array

k = np.linspace(0,10,5) # create an array with 5 values evenly spaced between 0 and 10
print(k) # print the array

l = np.random.randint(1,100,10) # create an array of 10 random integers between 1 and 100
print(l) # print the array of random integers

m = np.eye(3) # create a 3x3 identity matrix
print(m) # print the identity matrix



[4 5 6 7 8 9]
[[1 2 4 5]
 [7 9 6 9]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[ 5  7  9 11 13]
[ 0.   2.5  5.   7.5 10. ]
[18 38 19 98  1 22 77 24 17 53]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Array properties 

In [53]:
a = np.shape([4,5,6,7,8,9]) # create a 1D numpy array and get its shape
print(a) # print the array

b = np.array(([1,2,4,5],[7,9,6,9])) # create a 2D numpy array and get its shape
print(b) # print the 2D array
print(np.shape(b))
print(np.shape(b)[0]) # print the number of rows
print(np.shape(b)[1]) # print the number of columns
print(np.shape(b)[0]*np.shape(b)[1]) # print the total number of elements in the array
print("the total number of elements in the row : ", np.size(b,0)) # print the total number of elements in the array
print("the total number of elements in the column : ", np.size(b,1)) # print the total number of rows in the array

print(np.ndim(b)) # print the number of dimensions of the array





(6,)
[[1 2 4 5]
 [7 9 6 9]]
(2, 4)
2
4
8
the total number of elements in the row :  2
the total number of elements in the column :  4
2


# Basic Array Operations 

In [54]:
print(" add the two arrays together: ", a+b) # add the two arrays together
print(" subtract the two arrays: ", a-b) # subtract the two arrays
print(" multiply the two arrays: ", a*b) # multiply the two arrays
print(" divide the two arrays: ", a/b) # divide the two arrays     
print(" square the array: ", b**2) # square the array 
print(" add 10 to each element in the array: ", b +10) # add 10 to each element in the array
print(" subtract 10 from each element in the array: ", b - 10) # subtract 10 from each element in the array
print(" multiply each element in the array by 10: ", b * 10) # multiply each element in the array by 10
print(" divide each element in the array by 10: ", b / 10) # divide each element in the array by 10

# NOTE : The above operations will only work if the two arrays have the same shape. If they do not, you will get a ValueError.

 add the two arrays together:  [[ 7  8 10 11]
 [13 15 12 15]]
 subtract the two arrays:  [[ 5  4  2  1]
 [-1 -3  0 -3]]
 multiply the two arrays:  [[ 6 12 24 30]
 [42 54 36 54]]
 divide the two arrays:  [[6.         3.         1.5        1.2       ]
 [0.85714286 0.66666667 1.         0.66666667]]
 square the array:  [[ 1  4 16 25]
 [49 81 36 81]]
 add 10 to each element in the array:  [[11 12 14 15]
 [17 19 16 19]]
 subtract 10 from each element in the array:  [[-9 -8 -6 -5]
 [-3 -1 -4 -1]]
 multiply each element in the array by 10:  [[10 20 40 50]
 [70 90 60 90]]
 divide each element in the array by 10:  [[0.1 0.2 0.4 0.5]
 [0.7 0.9 0.6 0.9]]


# PHYSICS APPLICATION

In [55]:
distance  = np.array([5,10,15,20,25]) #MPC
h0 = 70 # Hubble constant in km/s/Mpc
velocity = h0 * distance # calculate the velocity of each galaxy using Hubble's law
print("calculate recession velocity of each galaxy is: ", velocity) # print the velocity of each galaxy

calculate recession velocity of each galaxy is:  [ 350  700 1050 1400 1750]


## Day 1 Summary

Today I learned:
- Creating NumPy arrays using different functions.
- Understanding array properties (`shape`, `size`, `ndim`, `dtype`).
- Performing element-wise arithmetic operations.
- Using scalar operations on arrays.
- Applying NumPy to calculate galaxy recession velocities using Hubble's Law.

Key takeaway:
NumPy enables fast vectorized computations, making it essential for scientific computing, astrostatistics, and cosmology.
- 