# Day 3 Numpy Mathematical & statistical operations

### Part 1 : Mathematical functions

In [14]:
import numpy as np
a = np.array([7,8,5,3,5,4])
b = np.array([[3,5],[7,8]])

# square root of a and b arrays
print("Square root of a:", np.sqrt(a))
print("Square root of b:")
print(np.sqrt(b))
print()

# square of a and b arrays
print("Square of a:", np.square(a))
print("Square of b:")
print(np.square(b))
print()

#exponential of a and b arrays
print("Exponential of a:", np.exp(a))
print("Exponential of b:",np.exp(b))
print()

#logarithm of a and b arrays
print("Logarithm of a:", np.log(a))
print("Logarithm of b:")
print(np.log(b))
print()

#sine of a and b arrays
print("Sine of a:", np.sin(a))
print("Sine of b:")
print(np.sin(b))
print()

Square root of a: [2.64575131 2.82842712 2.23606798 1.73205081 2.23606798 2.        ]
Square root of b:
[[1.73205081 2.23606798]
 [2.64575131 2.82842712]]

Square of a: [49 64 25  9 25 16]
Square of b:
[[ 9 25]
 [49 64]]

Exponential of a: [1096.63315843 2980.95798704  148.4131591    20.08553692  148.4131591
   54.59815003]
Exponential of b: [[  20.08553692  148.4131591 ]
 [1096.63315843 2980.95798704]]

Logarithm of a: [1.94591015 2.07944154 1.60943791 1.09861229 1.60943791 1.38629436]
Logarithm of b:
[[1.09861229 1.60943791]
 [1.94591015 2.07944154]]

Sine of a: [ 0.6569866   0.98935825 -0.95892427  0.14112001 -0.95892427 -0.7568025 ]
Sine of b:
[[ 0.14112001 -0.95892427]
 [ 0.6569866   0.98935825]]



### Basic Statistics