## Matrix and its operation through numpy

In [ ]:
import numpy as np

#create matrix using numpy
A = np.array([
    [1,5,8],
    [8,5,4]
])
print(A)
print(A.shape) # dimensions of the array
print(A.ndim) # number of dimensions
print(A.size) # total number of elements
print(A.dtype) # data type of the elements
print()

#creating 3*3 matrix using numpy
B = np.array([
    [8,9,1],
    [78,95,34],
    [32,54,64]
])
print(B)
print(B.shape) # dimensions of the array
print(B.ndim) # number of dimensions
print(B.size) # total number of elements
print()

# zeros matrix syntax: np.zeros((rows,columns))
# the double parentheses are because the shape is given as a tuple.
C = np.zeros((4,4))
print(C.dtype) # data type of the elements
print(C.shape) # dimensions of the array
print(C.ndim) # number of dimensions
print(C.size) # total number of elements
print(C)
print()

#similar with ones matrix
D = np.ones((2,5))
print(D.shape) # dimensions of the array
print(D.ndim) # number of dimensions
print(D.size) # total number of elements  
print(D.dtype) # data type of the elements  
print(D)
print()

#now identity matrix
E = np.eye(4)
print(E)
print(E.shape) # dimensions of the array
print(E.ndim) # number of dimensions
print(E.size) # total number of elements
print(E.dtype) # data type of the elements
print()





[[1 5 8]
 [8 5 4]]
(2, 3)
2
6
int64

[[ 8  9  1]
 [78 95 34]
 [32 54 64]]
(3, 3)
2
9

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Matrix addition and substraction 


In [ ]:
# creating a matrix with 3x3

F = np.array([
    [1,9,3],
    [4,5,3],
    [5,8,9]
])
print(F)
print()

G= np.array([
    [1,2,3],
    [4,9,6],
    [7,0,9]
])
print(G)
print()

# Adding two matrices 
H = F + G
print(H)
print()
# Subtracting two matrices
H = F-G
print(H)
print()

I = G-F
print(I)
print()
#adding a scalar to a matrix
J = F + 5
print(J)


[[1 9 3]
 [4 5 3]
 [5 8 9]]

[[1 2 3]
 [4 9 6]
 [7 0 9]]

[[ 2 11  6]
 [ 8 14  9]
 [12  8 18]]

[[ 0  7  0]
 [ 0 -4 -3]
 [-2  8  0]]

[[ 0 -7  0]
 [ 0  4  3]
 [ 2 -8  0]]

[[ 6 14  8]
 [ 9 10  8]
 [10 13 14]]


### scalar multiplication

In [ ]:
# create a matrix and multiply it by a scalar
# scalar multiplication is done by multiplying each 
# element of the matrix by the scalar value.

K = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

L = 5*K
print(L)

M = -3*K
print(M)

N = 9.8*K
print(N)


[[ 5 10 15]
 [20 25 30]]
[[ -3  -6  -9]
 [-12 -15 -18]]
[[ 9.8 19.6 29.4]
 [39.2 49.  58.8]]
