## Part1 mathematical function 

In [1]:
import numpy as np

a = np.array([7, 8, 5, 3, 5, 4])

b = np.array([
    [3, 5],
    [7, 8]
])

print("Square root of a:", np.sqrt(a))
print()
print("Square root of b:")
print(np.sqrt(b))
print()

print("Square of a:", np.square(a))
print()
print("Square of b:")
print(np.square(b))
print()

print("Exponential of a:", np.exp(a))
print()
print("Exponential of b:")
print(np.exp(b))
print()

print("Natural log of a:", np.log(a))
print()
print("Natural log of b:")
print(np.log(b))
print()

print("Sine of a:", np.sin(a))
print()
print("Sine of b:")
print(np.sin(b))
print()

print("Cosine of a:", np.cos(a))
print()
print("Cosine of b:")
print(np.cos(b))

Square root of a: [2.64575131 2.82842712 2.23606798 1.73205081 2.23606798 2.        ]

Square root of b:
[[1.73205081 2.23606798]
 [2.64575131 2.82842712]]

Square of a: [49 64 25  9 25 16]

Square of b:
[[ 9 25]
 [49 64]]

Exponential of a: [1096.63315843 2980.95798704  148.4131591    20.08553692  148.4131591
   54.59815003]

Exponential of b:
[[  20.08553692  148.4131591 ]
 [1096.63315843 2980.95798704]]

Natural log of a: [1.94591015 2.07944154 1.60943791 1.09861229 1.60943791 1.38629436]

Natural log of b:
[[1.09861229 1.60943791]
 [1.94591015 2.07944154]]

Sine of a: [ 0.6569866   0.98935825 -0.95892427  0.14112001 -0.95892427 -0.7568025 ]

Sine of b:
[[ 0.14112001 -0.95892427]
 [ 0.6569866   0.98935825]]

Cosine of a: [ 0.75390225 -0.14550003  0.28366219 -0.9899925   0.28366219 -0.65364362]

Cosine of b:
[[-0.9899925   0.28366219]
 [ 0.75390225 -0.14550003]]


## Part 2 — Basic Statistical Operations

In [2]:
data = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard deviation:", np.std(data))
print("Variance:", np.var(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Sum:", np.sum(data))

Mean: 30.0
Median: 30.0
Standard deviation: 14.142135623730951
Variance: 200.0
Minimum: 10
Maximum: 50
Sum: 150


## Part 3 — Mean vs Median

In [ ]:
temp = np.array([10, 11, 12, 13, 14, 100])

print("Mean of temp:", np.mean(temp))
print("Median of temp:", np.median(temp))

Mean of temp: 26.666666666666668
Median of temp: 12.5


The extreme value 100 strongly affects the mean, while the median is much less affected.

## Part 4 — Understanding axis

In [4]:
data = np.array([
    [5000, 5100, 5050],
    [6000, 6100, 6050],
    [7000, 7100, 7050],
    [8000, 8100, 8050]
])

print("Data:")
print(data)

print()
print("Mean of entire dataset:")
print(np.mean(data))

print()
print("Mean along axis=0:")
print(np.mean(data, axis=0))

print()
print("Mean along axis=1:")
print(np.mean(data, axis=1))

Data:
[[5000 5100 5050]
 [6000 6100 6050]
 [7000 7100 7050]
 [8000 8100 8050]]

Mean of entire dataset:
6550.0

Mean along axis=0:
[6500. 6600. 6550.]

Mean along axis=1:
[5050. 6050. 7050. 8050.]


axis=0 → column-wise operation

axis=1 → row-wise operation

## Part 5 — Astronomy: Stellar Temperatures

In [5]:
temperature = np.array([
    3200, 3500, 4100, 4500, 5200,
    5800, 6200, 7000, 8500, 10000
])

print("Mean temperature:", np.mean(temperature))
print("Median temperature:", np.median(temperature))
print("Standard deviation:", np.std(temperature))
print("Variance:", np.var(temperature))
print("Minimum temperature:", np.min(temperature))
print("Maximum temperature:", np.max(temperature))

Mean temperature: 5800.0
Median temperature: 5500.0
Standard deviation: 2086.1447696648474
Variance: 4352000.0
Minimum temperature: 3200
Maximum temperature: 10000


## Part 6 — Combine Day 2 + Day 3

In [6]:
hot_stars = temperature[temperature > 6000]

print("Hot stars:")
print(hot_stars)

print()
print("Mean temperature of hot stars:", np.mean(hot_stars))
print("Median temperature of hot stars:", np.median(hot_stars))
print("Standard deviation:", np.std(hot_stars))
print("Minimum:", np.min(hot_stars))
print("Maximum:", np.max(hot_stars))

Hot stars:
[ 6200  7000  8500 10000]

Mean temperature of hot stars: 7925.0
Median temperature of hot stars: 7750.0
Standard deviation: 1454.9484526951462
Minimum: 6200
Maximum: 10000


## Part 7 — Hubble Constant Measurements

In [7]:
H0 = np.array([
    69.8, 70.2, 69.5,
    70.1, 69.9, 70.4, 69.7
])

print("Mean H0:", np.mean(H0))
print("Median H0:", np.median(H0))
print("Standard deviation:", np.std(H0))
print("Minimum H0:", np.min(H0))
print("Maximum H0:", np.max(H0))

Mean H0: 69.94285714285714
Median H0: 69.9
Standard deviation: 0.2871393034605978
Minimum H0: 69.5
Maximum H0: 70.4


## Day 3 Summary

Today I learned:

- NumPy mathematical functions such as sqrt, square, exp, log, sin and cos.
- Statistical operations such as mean, median, standard deviation, variance, minimum, maximum and sum.
- The effect of outliers on the mean and median.
- The meaning of axis=0 and axis=1 in a 2D array.
- How to combine Boolean masking with statistical analysis.
- How NumPy can be applied to astronomical datasets such as stellar temperature.

### Key Takeaway

NumPy allows mathematical and statistical analysis of scientific datasets efficiently without using loops.