# Slicing and Indexing 

In [2]:
import numpy as np 
a = np.array([56,78,34,56,42,52,51]) # creating 1D array using numpy 
print(a)
print("First element:", a[0]) # Accessing the first element of the array
print("Last element:", a[-1]) # Accessing the last element of the array
print("Second last element:", a[-2]) # Accessing the second last element of the array

[56 78 34 56 42 52 51]
First element: 56
Last element: 51
Second last element: 52


In [3]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]]) # creating 2D array using numpy
print(b)
print("row 2:", b[1]) # Accessing the row 2 
print("row 3:", b[2]) # Accessing the row 3
print("column 3:", b[:,2]) # Accessing the column 3


[[1 2 3]
 [4 5 6]
 [7 8 9]]
row 2: [4 5 6]
row 3: [7 8 9]
column 3: [3 6 9]


### Modify array 

In [7]:
a[3] = 150 # Updating the 4th element of the array
print("Updated array:", a) # Printing the updated array
b[1,2] = 99 # Updating the element at row 2, column 3 of the 2D array
print("Updated 2D array:\n ", b) # Printing the updated 2D array 

Updated array: [ 56  78  34 150  42  52  51]
Updated 2D array:
  [[ 1  2  3]
 [ 4  5 99]
 [ 7  8  9]]


### Boolean Conditions and Masking

In [25]:
temp = np.array([4500, 5600, 6700, 7800, 8900]) # creating a new array
print(temp > 6000) # Creating a boolean array based on the condition
print(temp >= 7800)

print(temp[temp > 6000]) # Accessing the elements of the array that satisfy the condition
print(temp[temp >= 7800]) # Accessing the elements of the array that satisfy the condition

temp_2 = np.array([4000, 4500, 5000, 5500, 6000, 6500, 7000]) # creating a new array
print(temp_2[(temp_2 > 5000) & (temp_2 < 7000)]) # and operator to access the elements of the array that satisfy both conditions
print(temp_2[(temp_2 < 5000) | (temp_2 > 7000)]) # or operator to access the elements of the array that satisfy either condition
print(temp_2[~(temp_2 > 5000)]) # Accessing the elements of the array that do not satisfy the condition


[False False  True  True  True]
[False False False  True  True]
[6700 7800 8900]
[7800 8900]
[5500 6000 6500]
[4000 4500]
[4000 4500 5000]


### Astronomical Practice 


In [ ]:
galaxies_distance = np.array([1.2, 2.3, 3.4, 4.5, 5.6, 6.7, 7.8]) # creating a new array
print("First 3 galaxies distance :", galaxies_distance[:3]) # Accessing the first 3 elements of the array
print("Last 3 galaxies distance :", galaxies_distance[-3:]) # Accessing the last 3 elements of the array
print("Alternate galaxies distance :", galaxies_distance[::2]) # Accessing the alternate elements of the array or we write galaxies_distance[0:len(galaxies_distance):2]
print("far away galaxies from 3.4 Mpc :" , (galaxies_distance[galaxies_distance > 3.4]))
print("Number of far away galaxies from 3.4 Mpc :" , len(galaxies_distance[galaxies_distance > 3.4]))
print("galaxies distance between 2 Mpc and 6 Mpc :" , (galaxies_distance[(galaxies_distance > 2) & (galaxies_distance < 6)]))


First 3 galaxies distance : [1.2 2.3 3.4]
Last 3 galaxies distance : [5.6 6.7 7.8]
Alternate galaxies distance : [1.2 3.4 5.6 7.8]
far away galaxies from 3.4 Mpc : [4.5 5.6 6.7 7.8]
Number of far away galaxies from 3.4 Mpc : 4
galaxies distance between 2 Mpc and 6 Mpc : [2.3 3.4 4.5 5.6]


# more practice 

In [48]:
temperature = np.array([2500, 3000, 3500, 4000, 4500, 5000, 5500]) # creating a new array
print("cool stars temperature :", temperature[temperature < 4000]) # Accessing the elements of the array that satisfy the condition
print("sun like stars temperature :", temperature[(temperature >= 4000) & (temperature <= 6000)]) # Accessing the elements of the array that satisfy both conditions
print("hot stars temperature :", temperature[temperature > 5000]) # Accessing the elements of the array that satisfy the condition
print("reversing the array :", temperature[::-1]) # Reversing the array

cool stars temperature : [2500 3000 3500]
sun like stars temperature : [4000 4500 5000 5500]
hot stars temperature : [5500]
reversing the array : [5500 5000 4500 4000 3500 3000 2500]


## Day 2 Summary

Today I learned:
- NumPy array indexing and slicing.
- How to access individual elements and ranges of data.
- How to modify values in NumPy arrays.
- How Boolean conditions produce True/False masks.
- How Boolean masking filters scientific data.
- How to combine multiple conditions using `&` (AND) and `|` (OR).
- How to use `~` (NOT) to reverse a Boolean condition.
- How to reverse an array and select every second element using slicing.

### Scientific Application

I practiced filtering stellar-temperature data using NumPy. I selected cool stars, sun-like stars, and hot stars without using loops.

### Key Takeaway

Boolean masking allows scientific datasets to be filtered efficiently based on physical conditions, while slicing allows specific portions or patterns of an array to be selected.